version: "3"
services:
  api:
    image: mapringg/backend-oauth:latest
    ports:
      - "3333:3000"
    networks:
      - backend
    environment:
      - MONGODB_ENV=mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:3
    networks:
      - backend

networks:
  backend:
