version: "3"
services:
  api:
    build:
      context: .
    image: backend-oauth
    # image: mapringg/backend-oauth:latest
    ports:
      - "3000:3000"
    networks:
      - backend
    environment:
      - CORS_DEBUG=localhost
      - MONGODB_ENV=mongo
      - FRONTEND_ADDR=http://localhost
    depends_on:
      - mongo

  mongo:
    image: mongo:3
    networks:
      - backend

networks:
  backend:
