apiVersion: v1
kind: ConfigMap
metadata:
    name: frontend-config
data:
  config.js: |
    const config = (() => {
      return {
        "BACKEND_ADDR": "backend",
        "OAUTH_ADDR": "oauth"
      };
    })();