version: "3.7"
services:
  redis:
    image: redis
  sockets:
    build:
        context: .
    image: socket-server
    environment: 
        - REDIS_HOST=redis
        - CORS_ALLOW=localhost:5000
    ports: 
        - 3000:3000
    depends_on: 
        - redis